__author__ = 'Aleks'

'''
The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 
    1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. 

The first ten terms would be:
1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
'''

'''
Strategy: Straight-forward.
'''

import helpers.math_helper as mh
from abstract.AbstractSolution import AbstractSolution

class Euler12(AbstractSolution):

    def getSolution(self): return 76576500

    def solve(self, external_call=None):
        n = 0
        sum = 0
        num_of_divisors = 1

        while num_of_divisors < 501:
            sum += n

            num_of_divisors = len(mh.get_all_divisors(sum))

            if num_of_divisors > 500:
                return sum

            n += 1
